require('dotenv').config();
const axios = require('axios');

const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${GOOGLE_API_KEY}`;

/**
 * A more intelligent classification function that checks for AI refusal phrases.
 * @param {string} text - The text generated by the AI.
 * @returns {object} An object with the classification and reason.
 */
const classifyContent = (text) => {
    const lowercasedText = text.toLowerCase();

    // --- FIX ---
    // Added a check for common AI refusal phrases. This is the most important check.
    const refusalPhrases = [
        "i cannot fulfill",
        "i am unable to",
        "as a large language model",
        "my purpose is to be helpful and harmless",
        "violates my safety guidelines",
        "illegal or harmful activities",
        "unethical",
        "i cannot create"
    ];

    // If any refusal phrase is found, quarantine the post immediately.
    if (refusalPhrases.some(phrase => lowercasedText.includes(phrase))) {
        return { classification: 'quarantined', reason: 'AI refused to generate content due to a potential policy violation.' };
    }

    // --- Existing keyword checks ---
    if (lowercasedText.includes('sale') || lowercasedText.includes('discount') || lowercasedText.includes('buy now')) {
        return { classification: 'approved', reason: 'Contains promotional content.' };
    }
    if (lowercasedText.length < 15) {
        return { classification: 'quarantined', reason: 'Content is too short, may lack substance.' };
    }

    // If no violations are found, approve the content.
    return { classification: 'approved', reason: 'Content appears safe and meets basic criteria.' };
};


exports.analyzeContent = async (prompt) => {
    console.log("🧠 Calling AI moderation service with prompt...");
    try {
        const payload = {
            contents: [{
                parts: [{ text: prompt }]
            }]
        };
        const { data } = await axios.post(GEMINI_API_URL, payload, {
            headers: { 'Content-Type': 'application/json' }
        });

        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
        
        // Use the updated, more intelligent classification function.
        const moderationResult = classifyContent(generatedText);

        console.log("🤖 AI Moderation Result:", moderationResult);
        return {
            ...moderationResult,
            generatedText: generatedText // Also return the generated text itself
        };

    } catch (error) {
        console.error("Error during AI content analysis:", error.response ? error.response.data : error.message);
        return {
            classification: 'quarantined',
            reason: 'An error occurred during AI analysis. Post has been quarantined for manual review.',
            generatedText: prompt // Return original prompt as fallback
        };
    }
};

